name: Publish

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*
    - name: Install dependencies
      run: |
        dotnet clean -c Release && dotnet nuget locals all --clear
        dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release /p:Version=${{ github.event.release.tag_name }} -p:PackageReleaseNotes="See https://github.com/Noggog/Loqui/releases/tag/${{ github.event.release.tag_name }}"
    - name: Test
      run: dotnet test -c Release --no-build
      
  publish:
    runs-on: windows-latest
    - name: Publish Loqui to Github
      uses: svenstaro/upload-release-action@v2
      with:
        file: Loqui/bin/Release/Loqui.*.nupkg
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.release.tag_name }}
        file_glob: "true"
    - name: Publish Loqui Generation to Github
      uses: svenstaro/upload-release-action@v2
      with:
        file: Loqui.Generation/bin/Release/Loqui.Generation.*.nupkg
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.release.tag_name }}
        file_glob: "true"
    - name: Publish to Nuget.org
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --no-symbols
